@startuml
class Hamburguesa {
    - panes: Pan[]
    - carne: Carne
    - primerExtra: NodoExtra
    - tamañoExtras: int

    + Hamburguesa(panSuperior: Pan, panInferior: Pan, carne: Carne)
    + agregarExtra(extra: Extra): void
    + agregarExtra(index: int, extra: Extra): void
    + eliminarExtra(index: int): void
    + actualizarExtra(index: int, nuevoExtra: Extra): void
    + encontrarExtraNombre(nombre: String): int
    + mostrar(): void
    + describir(): String
}

class NodoExtra {
    - extra: Extra
    - siguiente: NodoExtra

    + NodoExtra(extra: Extra)
    + getExtra(): Extra
    + setExtra(extra: Extra): void
    + getSiguiente(): NodoExtra
    + setSiguiente(siguiente: NodoExtra): void
}

Hamburguesa "1" -- "0..*" NodoExtra

@enduml