@startuml

class Hamburguesa {
    -Pan[] panes
    -Carne carne
    -NodoExtra primerExtra
    +Hamburguesa(Pan panSuperior, Pan panInferior, Carne carne)
    +void agregarExtra(Extra extra)
    + actualizarExtra(index: int, nuevoExtra: Extra): void 
    + eliminarExtra(index: int): void     
    + agregarExtraNombre(index: int, extra: Extra): void 
    + encontrarExtraNombre(nombre: String): int 
    +void mostrar()
    +void describir()
    -NodoExtra obtenerNodoEnIndice(index: int)
}

@enduml